; BOUNCE - generated by OMNI MockGenerator (deterministic template)
; genre: arcade | controls: A toggles ball speed
; mechanics: bounce, ball
; NROM-128. Sprite 0 lives in the OAM shadow at $$0200.

; ---- zero page ----
ballx = $00
bally = $01
dx = $02
dy = $03
speed = $04
padstate = $10
padprev  = $11
padtmp   = $12

.org $C000

RESET:
    SEI
    CLD
    LDX #$40
    STX $4017           ; disable APU frame IRQ
    LDX #$00
    STX $4010           ; disable DMC IRQs
    STX $2000           ; NMI off
    STX $2001           ; rendering off
    STX $4015           ; APU channels off
    DEX
    TXS                 ; SP = $FF
    INX                 ; X = 0

vblank1:
    BIT $2002
    BPL vblank1         ; PPU warm-up

    TXA                 ; A = 0
clear:
    STA $0000,X
    STA $0100,X
    STA $0200,X
    STA $0300,X
    STA $0400,X
    STA $0500,X
    STA $0600,X
    STA $0700,X
    INX
    BNE clear

vblank2:
    BIT $2002
    BPL vblank2

    ; palette upload during forced blank (rendering off: legal)
    LDA #$3F
    STA $2006
    LDA #$00
    STA $2006
    LDX #$00
pal_loop:
    LDA palette,X
    STA $2007
    INX
    CPX #$20
    BNE pal_loop

    LDA #$78
    STA ballx
    LDA #$6E
    STA bally
    LDA #$01
    STA dx
    STA dy
    STA speed
    ; sprite 0: ball
    LDA bally
    STA $0200
    LDA #$02
    STA $0201           ; tile 2 (ball)
    LDA #$00
    STA $0202
    LDA ballx
    STA $0203
    CLI
    LDA #%10000000
    STA $2000           ; NMI on
    LDA #%00011110
    STA $2001           ; rendering on: bg + sprites
main:
    JMP main            ; idle; NMI does the work

NMI:
    PHA
    TXA
    PHA
    TYA
    PHA
        JSR read_pad
        ; A toggles speed 1x/2x (edge-triggered)
        LDA padstate
        AND #$80
        BEQ sp_rel
        LDA padprev
        BNE sp_done
        LDA speed
        EOR #$03            ; 1 <-> 2
        STA speed
        LDA #$80
        STA padprev
        JMP sp_done
    sp_rel:
        LDA #$00
        STA padprev
    sp_done:
        JSR move_ball
        LDA speed
        CMP #$02
        BNE spd_done
        JSR move_ball       ; 2x speed: integrate twice
    spd_done:
        LDA bally
        STA $0200
        LDA ballx
        STA $0203
    LDA #$02
    STA $4014           ; OAM DMA from $0200
    PLA
    TAY
    PLA
    TAX
    PLA
    RTI

IRQ:
    RTI

; controller 1 -> padstate. Bits: 7=A 6=B 5=Select 4=Start 3=Up 2=Down 1=Left 0=Right
read_pad:
    LDA #$01
    STA $4016
    LDA #$00
    STA $4016           ; strobe
    LDX #$08
rp_loop:
    LDA $4016
    LSR A               ; bit 0 -> carry
    ROL padstate
    DEX
    BNE rp_loop
    RTS

; ---- subroutines ----
    ; integrate position, bouncing off the walls (X: 0..239, Y: 16..223)
    move_ball:
        LDA ballx
        CLC
        ADC dx
        STA ballx
        LDX dx
        CPX #$01
        BEQ mx_right
        CMP #$FF            ; wrapped below 0?
        BNE mx_done
        LDA #$01
        STA dx
        LDA #$00
        STA ballx
        JMP mx_done
    mx_right:
        BCS mx_hit_r        ; wrapped past 255
        CMP #$F0
        BCC mx_done
    mx_hit_r:
        LDA #$FF
        STA dx
        LDA #$EF
        STA ballx
    mx_done:
        LDA bally
        CLC
        ADC dy
        STA bally
        LDX dy
        CPX #$01
        BEQ my_down
        CMP #$FF
        BNE my_done
        LDA #$01
        STA dy
        LDA #$10
        STA bally
        JMP my_done
    my_down:
        BCS my_hit_b
        CMP #$E0
        BCC my_done
    my_hit_b:
        LDA #$FF
        STA dy
        LDA #$DF
        STA bally
    my_done:
        RTS

palette:
    .byte $0F,$0F,$0F,$0F, $0F,$16,$26,$36, $0F,$0F,$0F,$0F, $0F,$0F,$0F,$0F
    .byte $0F,$0F,$0F,$0F, $0F,$16,$26,$36, $0F,$0F,$0F,$0F, $0F,$0F,$0F,$0F

    .org $FFFA
    .word NMI, RESET, IRQ
