; SCORE RALLY - generated by OMNI MockGenerator (deterministic template)
; genre: arcade | controls: D-pad moves, A scores
; mechanics: score, counter, move
; NROM-128. Sprite 0 lives in the OAM shadow at $$0200.

; ---- zero page ----
score0 = $00
score1 = $01
score2 = $02
score3 = $03
framectr = $04
padstate = $10
padprev  = $11
padtmp   = $12

.org $C000

RESET:
    SEI
    CLD
    LDX #$40
    STX $4017           ; disable APU frame IRQ
    LDX #$00
    STX $4010           ; disable DMC IRQs
    STX $2000           ; NMI off
    STX $2001           ; rendering off
    STX $4015           ; APU channels off
    DEX
    TXS                 ; SP = $FF
    INX                 ; X = 0

vblank1:
    BIT $2002
    BPL vblank1         ; PPU warm-up

    TXA                 ; A = 0
clear:
    STA $0000,X
    STA $0100,X
    STA $0200,X
    STA $0300,X
    STA $0400,X
    STA $0500,X
    STA $0600,X
    STA $0700,X
    INX
    BNE clear

vblank2:
    BIT $2002
    BPL vblank2

    ; palette upload during forced blank (rendering off: legal)
    LDA #$3F
    STA $2006
    LDA #$00
    STA $2006
    LDX #$00
pal_loop:
    LDA palette,X
    STA $2007
    INX
    CPX #$20
    BNE pal_loop

    ; sprite 0: player block at (120,120)
    LDA #$78
    STA $0200
    LDA #$01
    STA $0201
    LDA #$00
    STA $0202
    LDA #$78
    STA $0203
    ; sprites 1-4: score digits at Y=116, X=112..136
    LDA #$74
    STA $0204
    STA $0208
    STA $020C
    STA $0210
    LDA #$10
    STA $0205
    STA $0209
    STA $020D
    STA $0211
    LDA #$00
    STA $0206
    STA $020A
    STA $020E
    STA $0212
    LDA #$70
    STA $0207
    LDA #$78
    STA $020B
    LDA #$80
    STA $020F
    LDA #$88
    STA $0213
    CLI
    LDA #%10000000
    STA $2000           ; NMI on
    LDA #%00011110
    STA $2001           ; rendering on: bg + sprites
main:
    JMP main            ; idle; NMI does the work

NMI:
    PHA
    TXA
    PHA
    TYA
    PHA
        JSR read_pad
        LDA padstate
        AND #$08            ; Up
        BEQ no_up
        LDA $0200
        SEC
        SBC #$01
        CMP #$10
        BCC no_up           ; clamp top
        STA $0200
    no_up:
        LDA padstate
        AND #$04            ; Down
        BEQ no_down
        LDA $0200
        CLC
        ADC #$01
        CMP #$E8
        BCS no_down         ; clamp bottom
        STA $0200
    no_down:
        LDA padstate
        AND #$02            ; Left
        BEQ no_left
        LDA $0203
        SEC
        SBC #$01
        CMP #$08
        BCC no_left         ; clamp left
        STA $0203
    no_left:
        LDA padstate
        AND #$01            ; Right
        BEQ no_right
        LDA $0203
        CLC
        ADC #$01
        CMP #$F8
        BCS no_right        ; clamp right
        STA $0203
    no_right:
        ; A scores (edge-triggered)
        LDA padstate
        AND #$80
        STA padtmp
        BEQ a_skip
        LDA padprev
        AND #$80
        BNE a_skip
        JSR inc_score
    a_skip:
        LDA padtmp
        STA padprev
        ; auto-tick: +1 every 30 frames
        INC framectr
        LDA framectr
        CMP #$1E
        BCC tick_done
        LDA #$00
        STA framectr
        JSR inc_score
    tick_done:
        ; digits -> tiles (sprite i tile = 16 + digit)
        LDX #$00
        LDY #$00
    upd_loop:
        LDA score0,X
        CLC
        ADC #$10
        STA $0205,Y
        INX
        INY
        INY
        INY
        INY
        CPX #$04
        BCC upd_loop
    LDA #$02
    STA $4014           ; OAM DMA from $0200
    PLA
    TAY
    PLA
    TAX
    PLA
    RTI

IRQ:
    RTI

; controller 1 -> padstate. Bits: 7=A 6=B 5=Select 4=Start 3=Up 2=Down 1=Left 0=Right
read_pad:
    LDA #$01
    STA $4016
    LDA #$00
    STA $4016           ; strobe
    LDX #$08
rp_loop:
    LDA $4016
    LSR A               ; bit 0 -> carry
    ROL padstate
    DEX
    BNE rp_loop
    RTS

; ---- subroutines ----
    ; +1 to the 4-digit score with decimal carry
    inc_score:
        LDX #$00
    isc_loop:
        INC score0,X
        LDA score0,X
        CMP #$0A
        BCC isc_done
        LDA #$00
        STA score0,X
        INX
        CPX #$04
        BCC isc_loop
    isc_done:
        RTS

palette:
    .byte $0F,$0F,$0F,$0F, $0F,$16,$26,$36, $0F,$0F,$0F,$0F, $0F,$0F,$0F,$0F
    .byte $0F,$0F,$0F,$0F, $0F,$16,$26,$36, $0F,$0F,$0F,$0F, $0F,$0F,$0F,$0F

    .org $FFFA
    .word NMI, RESET, IRQ
