; DPAD MOVE - generated by OMNI MockGenerator (deterministic template)
; genre: arcade | controls: D-pad moves, A cycles tile, B cycles palette
; mechanics: move, dpad, sprite
; NROM-128. Sprite 0 lives in the OAM shadow at $$0200.

; ---- zero page ----
padstate = $10
padprev  = $11
padtmp   = $12

.org $C000

RESET:
    SEI
    CLD
    LDX #$40
    STX $4017           ; disable APU frame IRQ
    LDX #$00
    STX $4010           ; disable DMC IRQs
    STX $2000           ; NMI off
    STX $2001           ; rendering off
    STX $4015           ; APU channels off
    DEX
    TXS                 ; SP = $FF
    INX                 ; X = 0

vblank1:
    BIT $2002
    BPL vblank1         ; PPU warm-up

    TXA                 ; A = 0
clear:
    STA $0000,X
    STA $0100,X
    STA $0200,X
    STA $0300,X
    STA $0400,X
    STA $0500,X
    STA $0600,X
    STA $0700,X
    INX
    BNE clear

vblank2:
    BIT $2002
    BPL vblank2

    ; palette upload during forced blank (rendering off: legal)
    LDA #$3F
    STA $2006
    LDA #$00
    STA $2006
    LDX #$00
pal_loop:
    LDA palette,X
    STA $2007
    INX
    CPX #$20
    BNE pal_loop

    ; sprite 0: player block at (120,120)
    LDA #$78
    STA $0200           ; Y
    LDA #$01
    STA $0201           ; tile 1 (player)
    LDA #$00
    STA $0202           ; attributes
    LDA #$78
    STA $0203           ; X
    CLI
    LDA #%10000000
    STA $2000           ; NMI on
    LDA #%00011110
    STA $2001           ; rendering on: bg + sprites
main:
    JMP main            ; idle; NMI does the work

NMI:
    PHA
    TXA
    PHA
    TYA
    PHA
        JSR read_pad
        LDA padstate
        AND #$08            ; Up
        BEQ no_up
        LDA $0200
        SEC
        SBC #$01
        CMP #$10
        BCC no_up           ; clamp top
        STA $0200
    no_up:
        LDA padstate
        AND #$04            ; Down
        BEQ no_down
        LDA $0200
        CLC
        ADC #$01
        CMP #$E8
        BCS no_down         ; clamp bottom
        STA $0200
    no_down:
        LDA padstate
        AND #$02            ; Left
        BEQ no_left
        LDA $0203
        SEC
        SBC #$01
        CMP #$08
        BCC no_left         ; clamp left
        STA $0203
    no_left:
        LDA padstate
        AND #$01            ; Right
        BEQ no_right
        LDA $0203
        CLC
        ADC #$01
        CMP #$F8
        BCS no_right        ; clamp right
        STA $0203
    no_right:
        ; A cycles tile, B cycles attributes
        LDA padstate
        AND #$80
        BEQ no_a
        LDA padprev
        AND #$80
        BNE no_a
        INC $0201
        LDA $0201
        CMP #$04
        BCC a_done
        LDA #$01
        STA $0201
    a_done:
    no_a:
        LDA padstate
        AND #$40
        BEQ no_b
        LDA padprev
        AND #$40
        BNE no_b
        INC $0202
    no_b:
        LDA padstate
        STA padprev
    LDA #$02
    STA $4014           ; OAM DMA from $0200
    PLA
    TAY
    PLA
    TAX
    PLA
    RTI

IRQ:
    RTI

; controller 1 -> padstate. Bits: 7=A 6=B 5=Select 4=Start 3=Up 2=Down 1=Left 0=Right
read_pad:
    LDA #$01
    STA $4016
    LDA #$00
    STA $4016           ; strobe
    LDX #$08
rp_loop:
    LDA $4016
    LSR A               ; bit 0 -> carry
    ROL padstate
    DEX
    BNE rp_loop
    RTS

palette:
    .byte $0F,$0F,$0F,$0F, $0F,$16,$26,$36, $0F,$0F,$0F,$0F, $0F,$0F,$0F,$0F
    .byte $0F,$0F,$0F,$0F, $0F,$16,$26,$36, $0F,$0F,$0F,$0F, $0F,$0F,$0F,$0F

    .org $FFFA
    .word NMI, RESET, IRQ
