#!/usr/bin/env python3
"""
Generate R.java for every library package from the LINKED resource table.

Background: aapt2 link merges all library resources under the app package
(com.omni.app) and only emits R.java for that package. But library bytecode
references <lib-package>.R$<type>.<name> fields, so we synthesize those R
classes with the merged IDs from `aapt2 dump resources`.

Styleables: `aapt2 dump resources` does not list styleable entries, so for
androidx.core (the only package whose bytecode references R$styleable) the
styleable arrays are synthesized from the AAR's declare-styleable XML plus
framework attr IDs (android.R.attr, stable 0x0101xxxx constants).

Usage:
    python3 gen_lib_r.py --dump res-dump.txt --extract extract/EXTRACT.tsv \
        --out gen-r-lib
"""
import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET

# framework attr IDs (android.R.attr) needed by androidx.core styleables.
# From android.jar (platform android-36) via javap -constants.
FW_ATTR = {
    "color": 0x10101a5, "offset": 0x1010514, "font": 0x1010532,
    "fontStyle": 0x101053f, "fontVariationSettings": 0x1010570,
    "fontWeight": 0x1010533, "ttcIndex": 0x101056f, "alpha": 0x101031f,
    "lStar": 0x1010647, "centerColor": 0x101020b, "centerX": 0x10101a2,
    "centerY": 0x10101a3, "endColor": 0x101019e, "endX": 0x1010512,
    "endY": 0x1010513, "gradientRadius": 0x10101a4, "startColor": 0x101019d,
    "startX": 0x1010510, "startY": 0x1010511, "tileMode": 0x1010201,
    "type": 0x10101a1,
}

CORE_STYLEABLES = ("GradientColor", "GradientColorItem", "FontFamily",
                   "FontFamilyFont", "ColorStateListItem", "Capability")


def log(*a):
    print(*a, flush=True)


def parse_dump(path):
    res = {}  # (type, name) -> id int
    pat = re.compile(r"^\s*resource (0x[0-9a-fA-F]+) ([a-z0-9_]+)/([A-Za-z0-9_.$-]+)")
    for line in open(path, encoding="utf-8", errors="replace"):
        m = pat.match(line)
        if m:
            rid, rtype, rname = m.group(1), m.group(2), m.group(3)
            # sanitize to java identifier (aapt2 names are already clean; be safe)
            jname = re.sub(r"[^A-Za-z0-9_]", "_", rname)
            if (rtype, jname) not in res:
                res[(rtype, jname)] = int(rid, 16)
    return res


def core_styleables(extract_dir):
    """Parse declare-styleables from the androidx.core AAR res."""
    out = {}
    vals = os.path.join(extract_dir, "androidx.core__core__1.13.1", "res", "values", "values.xml")
    # fall back: find any core res dir
    if not os.path.exists(vals):
        for d in os.listdir(extract_dir):
            if d.startswith("androidx.core__core__"):
                cand = os.path.join(extract_dir, d, "res", "values", "values.xml")
                if os.path.exists(cand):
                    vals = cand
                    break
    root = ET.parse(vals).getroot()
    for ds in root.iter("declare-styleable"):
        name = ds.get("name")
        if name in CORE_STYLEABLES:
            attrs = []
            for a in ds.iter("attr"):
                n = a.get("name")
                if n.startswith("android:"):
                    attrs.append(("fw", n.split(":", 1)[1]))
                else:
                    attrs.append(("app", n))
            out[name] = attrs
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", required=True)
    ap.add_argument("--extract", required=True)   # extract dir (for EXTRACT.tsv + res)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    res = parse_dump(args.dump)
    log(f"parsed {len(res)} resources from dump")
    types = sorted({t for t, _ in res})

    tsv = os.path.join(args.extract, "EXTRACT.tsv")
    pkgs = set()
    for line in open(tsv):
        parts = line.rstrip("\n").split("\t")
        if parts and parts[0]:
            pkgs.add(parts[0])
    # the app package R is already generated by aapt2; skip it here
    pkgs.discard("com.omni.app")
    log(f"library packages: {len(pkgs)}")

    core_sty = core_styleables(args.extract)
    log(f"core styleables parsed: {sorted(core_sty)}")

    missing = []
    for pkg in sorted(pkgs):
        lines = [f"package {pkg};", "", "public final class R {"]
        for t in types:
            lines.append(f"  public static final class {t} {{")
            for (rt, name), rid in sorted(res.items()):
                if rt != t:
                    continue
                lines.append(f"    public static final int {name}=0x{rid:08x};")
            lines.append("  }")
        if pkg == "androidx.core":
            lines.append("  public static final class styleable {")
            for sname, attrs in core_sty.items():
                ids = []
                ok = True
                for kind, aname in attrs:
                    if kind == "fw":
                        rid = FW_ATTR.get(aname)
                        if rid is None:
                            missing.append(f"fw attr {aname}")
                            ok = False
                    else:
                        rid = res.get(("attr", aname))
                        if rid is None:
                            missing.append(f"app attr {aname}")
                            ok = False
                    ids.append(rid if rid is not None else 0)
                arr = ",".join(f"0x{i:08x}" for i in ids)
                lines.append(f"    public static final int[] {sname}={{{arr}}};")
                for idx, (kind, aname) in enumerate(attrs):
                    prefix = "android_" if kind == "fw" else ""
                    lines.append(f"    public static final int {sname}_{prefix}{aname}={idx};")
                if not ok:
                    log(f"  WARN: styleable {sname} has unresolved attrs")
            lines.append("  }")
        lines.append("}")
        out_path = os.path.join(args.out, *pkg.split("."), "R.java")
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w") as f:
            f.write("\n".join(lines) + "\n")
    if missing:
        log(f"WARN: missing attrs: {sorted(set(missing))}")
    n = sum(1 for _d, _ds, fs in os.walk(args.out) for f in fs if f == "R.java")
    log(f"wrote {n} R.java files -> {args.out}")


if __name__ == "__main__":
    main()
